# Generated by Django 4.1.7 on 2023-03-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='an_asigned_truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(default='no truck assigned', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('language', models.CharField(choices=[('BM', 'BM'), ('BI', 'BI'), ('BC', 'BC')], default='BM', max_length=100)),
                ('city_district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='citys', to='API.city')),
                ('truck', models.ManyToManyField(default=1, related_name='trucks', to='API.an_asigned_truck')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100, null=True)),
                ('citys', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.city')),
            ],
        ),
    ]
