# Generated by Django 4.1.7 on 2023-03-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='city_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citys', to='API.city'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck',
            field=models.ManyToManyField(related_name='trucks', to='API.an_asigned_truck'),
        ),
    ]
